# Generated by Django 5.1.6 on 2025-05-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lineuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lineuser',
            name='user',
        ),
        migrations.AddField(
            model_name='lineuser',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='line_user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
