# Generated by Django 4.2.15 on 2024-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_data_form', '0007_product_is_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
