# Generated by Django 4.2.17 on 2024-12-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_data_form', '0008_market_invoice_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_data_form.market')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
