# Generated by Django 5.1.6 on 2025-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_data_form', '0010_transfer_existing_pdfs'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='market',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='unique_market_name_date'),
        ),
    ]
