# Generated by Django 4.2.17 on 2024-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_buyers_auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
