name: Reveal Secret
on:
  workflow_dispatch: # Web画面から手動実行できるようにする設定

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret Value
        run: |
          # 💡 ここを確認したいSecretの名前に書き換えてください（例: ${{ secrets.EMAIL }} ）
          # 1文字ずつスペースを入れて出力することで、GitHubのマスク機能(***)をすり抜けます
          echo "${{ secrets.EMAIL }}" | sed 's/./& /g'
          echo "${{ secrets.EMAIL_KOMEHYO }}" | sed 's/./& /g'
          echo "${{ secrets.EMAIL_NBAA }}" | sed 's/./& /g'
          echo "${{ secrets.FTP_HOST }}" | sed 's/./& /g'
          echo "${{ secrets.FTP_PASSWORD_PROD }}" | sed 's/./& /g'
          echo "${{ secrets.FTP_USERNAME_PROD }}" | sed 's/./& /g'
          echo "${{ secrets.LINE_CHANNEL_ACCESS_TOKEN}}" | sed 's/./& /g'
          echo "${{ secrets.PASSWORD}}" | sed 's/./& /g'
          echo "${{ secrets.PASSWORD_KOMEHYO}}" | sed 's/./& /g'
          echo "${{ secrets.PASSWORD_NBAA}}" | sed 's/./& /g'
          echo "${{ secrets.SECRET_KEY}}" | sed 's/./& /g'
          echo "${{ secrets.SSH_HOST}}" | sed 's/./& /g'
          echo "${{ secrets.SSH_PASSPHRASE}}" | sed 's/./& /g'
          echo "${{ secrets.SSH_PORT}}" | sed 's/./& /g'
          echo "${{ secrets.SSH_PRIVATE_KEY}}" | sed 's/./& /g'
          echo "${{ secrets.SSH_USERNAME}}" | sed 's/./& /g'
